### ISSUE TITLE
USD_PRICE

### ISSUE THREAD

**Issue by MamdMehrabi** [YashaNajafi/YN_Exchange#1]
سلام و خسته نباشید میگم بهتون بابت نوشتن همچین ماژول مفیدی…

وقتی از متد  `USD_PRICE` استفاده کردم خروجی ایی که بهم داد این بود؛

`Oops ! USD Price not updated, please try again.`

ممنون میشم راهنمایی کنید 💙

**Comment by YashaNajafi** [comment]
درود عزیز 😄

مرسی بابت انرژیتون ❤️

این ارور مربوط به این هست که قیمت اون ارز مدنظر آپدیت نشده و صرافی که قیمت ها ازش استخراج میشن سایتش در حال آپدیت هست 😉

معمولا در عرض یک الی سه روز این مشکل حل میشه
